// apps/vue-icestark-child/src/pages/Home/Home.vue
<template>
  <div>
    <div>小二：首页</div>
    <router-link to="/detail">detail</router-link>
    <br />
    <router-link to="/list">list</router-link>
    <br />
    <span>store=>{{info}}</span>
    <el-alert
      title="这是一个 Element 6的组件"
      type="success"
    >
    </el-alert>
  </div>
</template>

<script>
import { appHistory } from '@ice/stark-app';
import { mapState } from 'vuex'

export default {
  computed: {
    ...mapState(['info'])
  },
  mounted() {
    console.log(this.$store)
  },
  methods: {
    handleClick: () => {
      appHistory.push('/');
    }
  }
}
</script>

// apps/child-seller-react-16/src/pages/Home/index.js
import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { appHistory } from '@ice/stark-app';
import { Button } from '@alifd/next';
import IceContainer from '@icedesign/container';
import PageTitle from '@/components/PageTitle';

export default function Home() {

  useEffect(() => {
    console.log('Home Page mounted');
    return () => {
      console.log('Home Page unmounted');
    };
  }, []);

  return (
    <IceContainer>
      <PageTitle title="商家首页" />

      <Link to="/detail">子应用内跳转</Link>
      <br />
      <Button type="primary" onClick={() => {
        appHistory.push('/message');
      }}>子应用间跳转</Button>
      <br />
    </IceContainer>
  );
}
